Ready for code review
noomdalv/Building-with-Responsive-Design pull request #2
Opened 2019-08-05 22:47 UTC by noomdalv

2019-08-06 00:05 UTC, bolah2009 commented
Currently under review

2019-08-06 00:57 UTC, bolah2009 requested changes
## Nice Job Team :clap: 

The clone looks nice, however, I would suggest making it more responsive since the main objective of the project is to make a responsive clone of [this page](https://thenextweb.com/). See below (check the full [page](https://thenextweb.com/) for more section that needs to be responsive:

| Current | Preferred |
| :-----: | :-----: |
| ![tnw current](https://user-images.githubusercontent.com/36057474/62503656-0e815580-b7ed-11e9-8cf5-f1636bf89d83.gif) | ![tnw preffered](https://user-images.githubusercontent.com/36057474/62503665-18a35400-b7ed-11e9-9de5-d00f7707be17.gif) |

You can recreate this issue (Image above) by using the console on chrome **(Inspect `Ctrl+Shift+I`)** and the **Toggle device toolbar** `Ctrl+Shift+M`. This way you can simulate how the app will render on small to widescreen devices.

### Optional but strongly recommended

- Note [this comment](#discussion_r310841076) on using `wrap` as `flex-direction` value.

- Check out [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fnoomdalv%2FBuilding-with-Responsive-Design%2Ffeature-smallscreenprototype%2Findex.html) too.

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-06 00:57 UTC, bolah2009 commented on css/main.css
> +    flex-direction: wrap;
`SUGGESTION`

Consider changing to a correct value.

`flex-direction` does not have a `wrap` value. Possible values are `row` `row-reverse`, `column`, `column-reverse` and other global attributes. Learn more about `flex-direction` [here](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction)

2019-08-06 00:57 UTC, bolah2009 commented on index.html
> +            <li><a id="firstSectionTitleA" href="https://thenextweb.com/author/ben-dickson/">by Ben Dickson</a></li>
`SUGGESTION`

Consider using a unique ID. [See here]()

2019-08-06 00:57 UTC, bolah2009 commented on index.html
> +            <li><a id="firstSectionTitleA" href="https://thenextweb.com/author/napierLopez/">by Napier Lopez</a></li>
`SUGGESTION`

You seem to be using this ID more than once, as it appears [here]()

2019-08-08 00:49 UTC, Torres-ssf requested changes
### Nicely done team :clap: 
But before I give a :+1: we need to do a few changes to make your clone page behaves just like the original one (these are required by Microverse guidelines). They are:

- Latest news section

- [ ] Must aligns 3 articles per row in the medium version(4 is only for the large version).

- Latest Funding section

- [ ] Must aligns 3 articles per row in the medium version(4 is only for the large version).

- Categories (Apps, GERA, Tech, etc) section

- [ ] Must aligns 2 articles per row in the medium version(3 is only for the large version).

- Latest deals section

- [ ] Must aligns 3 articles per row in the medium version(4 is only for the large version).

Please kindly make these changes and submit for code review again!

2019-08-08 18:11 UTC, mosaaleb requested changes
## Well done @noomdalv, @SofiBretz :clap:

I see that you have put a lot of effort into this project. I admire your dedication but there is some requirement needs to be met before moving on.

### Large Screen:
- [ ] Navigation bar contain search icon at the rightmost side -- As seen on the the original page.


### Medium Screen

- [ ] Links are hiding behind the blocks as you can see. let's fix this
- [ ] Also each funding section header text is hiding behind the left thumbnail in All screen sizes.
![Screenshot from 2019-08-08 19-57-02](https://user-images.githubusercontent.com/4246637/62726134-c9d90280-ba16-11e9-9680-3d8e3670cbdd.png)

- [ ] Please, use [stickler](https://github.com/microverseinc/linters-config/tree/master/css). It doesn't take time to use and it makes sure that you have good styling guidelines.

- [ ] [OPTIONAL]: I highly recommend the start all of the coming projects using [`reset.css`] (https://meyerweb.com/eric/tools/css/reset/) file (except when you are using bootstrap as it is bundled by default with a reset file) , as you can you see there is some margin at the top of the page, this is default value and can change by browsers. Using `reset.css` file ensure that we have the same initial state in all browsers.


Please handle these requirements and submit a new code review.

### Happy Coding :computer:

2019-08-09 01:13 UTC, bolah2009 commented
Currently under review

2019-08-09 01:34 UTC, Ispirett commented
# Reviewing

2019-08-09 01:39 UTC, bolah2009 approved these changes
## Good Job Team :clap: 

The [clone](https://raw.githack.com/noomdalv/Building-with-Responsive-Design/feature-smallscreenprototype/index.html) looks good to me.

#### Friendly reminder: You should use [Linter](https://github.com/microverseinc/linters-config#linters-config) in this project. Please make sure you use it in the next project. You will find instructions in the Pathwright lesson description.

### Check the comment below before merging.

Good luck with your next project.

Cheers
[Bola](https://bolabuari.com/)

2019-08-09 01:39 UTC, bolah2009 commented on css/main.css
> +  #fifthSection {
`HINT`

You seem to be using only two breakpoints for the media query which is affecting the display of this section for smaller screens. See below:

| Current | Preferred |
| :-----: | :-----: |
| ![tnw current](https://user-images.githubusercontent.com/36057474/62747638-47b80080-ba4d-11e9-96b5-5efafb919936.png) | ![tnw preffered](https://user-images.githubusercontent.com/36057474/62747646-4d154b00-ba4d-11e9-86df-c51d342cb631.png) |

2019-08-09 03:09 UTC, noomdalv commented
Hi Bola, thank you for the review!
i just fixed the error and it should be ok now, last commit we were
changing something for the 1024px breakpoint and somehow missed that,
thanks again.
the latest deals section displays the elements in rows now, like this:

[image: image.png]


Bye!.

El jue., 8 de ago. de 2019 a la(s) 20:39, BOLA AHMED BUARI (
notifications@github.com) escribió:

> *@bolah2009* approved this pull request.
> Good Job Team 👏
>
> The clone
> <https://raw.githack.com/noomdalv/Building-with-Responsive-Design/feature-smallscreenprototype/index.html>
> looks good to me.
> Friendly reminder: You should use Linter
> <https://github.com/microverseinc/linters-config#linters-config> in this
> project. Please make sure you use it in the next project. You will find
> instructions in the Patwright lesson description. Check the comment below
> before merging.
>
> Good luck with your next project.
>
> Cheers
> Bola <https://bolabuari.com/>
> ------------------------------
>
> In css/main.css
> <https://github.com/noomdalv/Building-with-Responsive-Design/pull/2#discussion_r312301865>
> :
>
> > +}
>
> +
>
> +@media screen and (max-width: 1024px) {
>
> +  #fifthSection {
>
> +    grid-template-columns: repeat(3, 1fr);
>
> +    grid-template-rows: 40px 320px 320px 320px;
>
> +    margin-bottom: -50px;
>
> +  }
>
> +
>
> +  #latestDeals {
>
> +    grid-column: 1 / 4;
>
> +  }
>
> +}
>
> +
>
> +@media screen and (max-width: 768px) {
>
> +  #fifthSection {
>
>
> HINT
>
> You seem to be using only two breakpoints for the media query which is
> affecting the display of this section for smaller screens. See below:
> Current Preferred
> [image: tnw current]
> <https://user-images.githubusercontent.com/36057474/62747638-47b80080-ba4d-11e9-96b5-5efafb919936.png> [image:
> tnw preffered]
> <https://user-images.githubusercontent.com/36057474/62747646-4d154b00-ba4d-11e9-86df-c51d342cb631.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/noomdalv/Building-with-Responsive-Design/pull/2?email_source=notifications&email_token=AMKWIWSRDO2DXDPEVY5VBL3QDTDEFA5CNFSM4IJPOR62YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCBCELSY#pullrequestreview-272909771>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMKWIWVOXIM6J2TMPINCXWTQDTDEFANCNFSM4IJPOR6Q>
> .
>

2019-08-09 03:12 UTC, merged